### ISSUE TITLE
Wrong file name for the manifest

### ISSUE THREAD

**Issue by tampe125** [akeeba/com_datacompliance#34]
Manifest file for the package is named `pkg_datacompliance.xml`, but the `element` tag is `compliance`.  
This means that while uninstalling it, Joomla is looking for the file `pkg_compliance.xml`. Since it does not exist, the extension is impossible to uninstall.  
I would do the change by myself, but I'm not sure if there are any other side effects concerning the file name

**Comment by nikosdion** [comment]
I changed the package name to DataCompliance as it should have been. Can you please verify that it uninstalls now?

**Comment by tampe125** [comment]
Yes, it uninstalls fine.

**Comment by tampe125** [comment]
Closed by 7a56f491dc56ba24ec7509105440eefab3119479
