### ISSUE TITLE
export data

### ISSUE THREAD

**Issue by darekmer** [akeeba/com_datacompliance#36]
Akeeba Data Compliance - An unhandled Exception has been detected
1146 Table 'j4.lk2t5_ars_log' doesn't exist 
 File &lt;root&gt;/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php Line 141

The content below this point is for developers and power users.

Joomla 4.2.6 – PHP 7.4.33 on Linux
Debug information

Exception type: Joomla\Database\Exception\PrepareStatementFailureException

#0 /var/www/html/j4/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php(1048): Joomla\Database\Mysqli\MysqliStatement->__construct()
#1 /var/www/html/j4/libraries/vendor/joomla/database/src/DatabaseDriver.php(1900): Joomla\Database\Mysqli\MysqliDriver->prepareStatement()
#2 /var/www/html/j4/plugins/datacompliance/ars/src/Extension/ARS.php(216): Joomla\Database\DatabaseDriver->setQuery()
#3 /var/www/html/j4/libraries/vendor/joomla/event/src/Dispatcher.php(486): Joomla\Plugin\DataCompliance\ARS\Extension\ARS->onDataComplianceExportUser()
#4 /var/www/html/j4/libraries/src/Application/EventAware.php(107): Joomla\Event\Dispatcher->dispatch()
#5 /var/www/html/j4/administrator/components/com_datacompliance/src/Model/ExportModel.php(211): Joomla\CMS\Application\WebApplication->triggerEvent()
#6 /var/www/html/j4/administrator/components/com_datacompliance/src/Model/ExportModel.php(81): Akeeba\Component\DataCompliance\Administrator\Model\ExportModel->runPlugins()
#7 /var/www/html/j4/administrator/components/com_datacompliance/src/Model/ExportModel.php(147): Akeeba\Component\DataCompliance\Administrator\Model\ExportModel->exportSimpleXML()
#8 /var/www/html/j4/administrator/components/com_datacompliance/src/Model/ExportModel.php(50): Akeeba\Component\DataCompliance\Administrator\Model\ExportModel->exportXML()
#9 /var/www/html/j4/administrator/components/com_datacompliance/src/Controller/OptionsController.php(93): Akeeba\Component\DataCompliance\Administrator\Model\ExportModel->exportFormattedXML()
#10 /var/www/html/j4/administrator/components/com_datacompliance/src/Mixin/ControllerEventsTrait.php(79): Akeeba\Component\DataCompliance\Administrator\Controller\OptionsController->export()
#11 /var/www/html/j4/libraries/src/Dispatcher/ComponentDispatcher.php(143): Akeeba\Component\DataCompliance\Administrator\Controller\OptionsController->execute()
#12 /var/www/html/j4/administrator/components/com_datacompliance/src/Dispatcher/Dispatcher.php(37): Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch()
#13 /var/www/html/j4/libraries/src/Component/ComponentHelper.php(355): Akeeba\Component\DataCompliance\Administrator\Dispatcher\Dispatcher->dispatch()
#14 /var/www/html/j4/libraries/src/Application/AdministratorApplication.php(143): Joomla\CMS\Component\ComponentHelper::renderComponent()
#15 /var/www/html/j4/libraries/src/Application/AdministratorApplication.php(186): Joomla\CMS\Application\AdministratorApplication->dispatch()
#16 /var/www/html/j4/libraries/src/Application/CMSApplication.php(294): Joomla\CMS\Application\AdministratorApplication->doExecute()
#17 /var/www/html/j4/administrator/includes/app.php(61): Joomla\CMS\Application\CMSApplication->execute()
#18 /var/www/html/j4/administrator/index.php(32): require_once('/var/www/html/j...')
#19 {main}

**Comment by nikosdion** [comment]
If you do not have Akeeba Release System installed on your site you need to unpublish the “Data Compliance – Akeeba Release System” plugin.

**Comment by darekmer** [comment]
Thanks
