### ISSUE TITLE
500 Call to a member function getGroup() on null File &lt;root&gt;/layouts/joomla/searchtools/default/bar.php Line 29

### ISSUE THREAD

**Issue by bmdiarra** [akeeba/com_datacompliance#39]
Hello, on Data Compliance, if I click on "Profile Deletions" I have this error: "500 Call to a member function getGroup() on null
File &lt;root&gt;/layouts/joomla/searchtools/default/bar.php Line 29". I put the capture in attached file. Can I have a solution for this bug.
<img width="702" alt="Akeeba data compliance error" src="https://user-images.githubusercontent.com/48700651/227982398-18b6bd0f-442a-46fd-9cd3-629c477ac6b0.png">

**Comment by nikosdion** [comment]
Thank you! See changes in https://github.com/akeeba/com_datacompliance/commit/3e0064b1998edf9101f1d8e697c890988b964ea4
