### ISSUE TITLE
Attempted to load class "Helper" from namespace "HelixUltimate\Framework\Platform". Did you forget a "use" statement for another namespace?

### ISSUE THREAD

**Issue by bmdiarra** [akeeba/com_datacompliance#40]
Good evening,
In fact, I have this error in Data Compliance if I click on the "Delete your user account" button and I write the sentence "I UNDERSTAND" and I validate. After that even if I refresh and enter the site address. I still have the same error. Could I have a solution?

<img width="780" alt="Data Compliance Front Error" src="https://user-images.githubusercontent.com/48700651/228329067-4d754a9c-34fe-4fbb-b164-5c41aca64d77.png">

**Comment by nikosdion** [comment]
This error comes **from your template** as per your screenshot.

Please contact your template developer.

**Comment by bmdiarra** [comment]
Hello, if I also change template I have errors too. I think it's related to the user session. That is to say that the user is deleted but his session is not. Can you do something?

<img width="960" alt="Erreur Template Cassiopei 2" src="https://user-images.githubusercontent.com/48700651/228510241-857bba14-6354-483a-90a2-ced86d480841.png">

**Comment by nikosdion** [comment]
Issue with Joomla 4.2 not closing the session, see https://github.com/akeeba/com_datacompliance/commit/5fc6543e55eaac61e4735e6cd96255990b14cba5
