### ISSUE TITLE
How to export data from other components with Akeeba Data Compliance ?

### ISSUE THREAD

**Issue by bmdiarra** [akeeba/com_datacompliance#41]
Hello, thank you for the previous answers. It was a big help. Now when I export the data I only have the data from Joomla. Is it possible to export data from other components like Os Service Booking, Membership pro Admin Tools ect?

**Comment by nikosdion** [comment]
You'd need to write plugins for them. The same holds true for Joomla's com_privacy.

By the way, if an extension offers a Privacy plugin but not a DataCompliance one — no problem. DataCompliance CAN use Joomla's privacy plugins, as long as they are published.

Also, for what it's worth, Admin Tools does not store any personally identifiable information. Therefore there is nothing to export and nothing to delete — hence the lack of a Privacy or DataCompliance plugin for this component of ours.
